# Generated by Django 4.2.7 on 2024-07-20 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0003_alter_status_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='FutureStockSusbcriptionUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('notified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('future_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.futurestock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Future Stock Subscription User',
                'verbose_name_plural': 'Future Stock Subscription Users',
            },
        ),
    ]
