# Generated by Django 4.2.7 on 2024-07-20 21:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0004_futurestocksusbcriptionuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FutureStockSusbcriptionUser',
            new_name='FutureStockSubcription',
        ),
    ]
