# Generated by Django 4.2.7 on 2024-07-23 00:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0006_alter_futurestocksubcription_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FutureStockSubcription',
            new_name='FutureStockSubscription',
        ),
    ]
