# Generated by Django 4.2.7 on 2024-08-21 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_futurestocksubcription_futurestocksubscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
    ]
