# Generated by Django 4.2.7 on 2024-08-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_storestatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Sale status',
                'verbose_name_plural': 'Sale status',
            },
        ),
    ]
