# Generated by Django 4.2.7 on 2024-08-17 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_color_rename_colors_colorsnum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='colors_num',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.colorsnum'),
        ),
    ]
