# Generated by Django 4.2.7 on 2024-08-17 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_sale_colors_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='colors_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.colorsnum'),
        ),
        migrations.AlterField(
            model_name='set',
            name='points',
            field=models.IntegerField(),
        ),
    ]
