# Generated by Django 4.2.7 on 2024-08-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_set'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorsNum',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num', models.IntegerField(unique=True)),
                ('price', models.FloatField()),
                ('details', models.TextField()),
            ],
            options={
                'verbose_name': 'Colors Num',
                'verbose_name_plural': 'Colors Num',
            },
        ),
    ]
