# Generated by Django 4.2.7 on 2024-08-17 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_sale_created_at_alter_sale_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.TextField()),
            ],
            options={
                'verbose_name': 'Sale status',
                'verbose_name_plural': 'Sale status',
            },
        ),
        migrations.RenameModel(
            old_name='Status',
            new_name='StoreStatus',
        ),
        migrations.AlterModelOptions(
            name='storestatus',
            options={'verbose_name': 'Store status', 'verbose_name_plural': 'Store status'},
        ),
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.salestatus'),
        ),
    ]
