# Generated by Django 4.2.7 on 2024-08-17 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_salestatus_rename_status_storestatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.salestatus'),
        ),
    ]
