# Generated by Django 4.2.7 on 2024-08-21 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0015_promocodes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('logo', models.ImageField(upload_to='')),
                ('full_name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=255)),
                ('street_address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('total', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('addons', models.ManyToManyField(to='store.addon')),
                ('color_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_set', to='store.color')),
                ('colors_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.colorsnum')),
                ('logo_color_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logo_color_1', to='store.color')),
                ('logo_color_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logo_color_2', to='store.color')),
                ('logo_color_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logo_color_3', to='store.color')),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.promocodes')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.set')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.salestatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
            },
        ),
    ]
