# Generated by Django 4.2.7 on 2024-08-21 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='logo_color_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logo_color_1', to='store.color'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='logo_color_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logo_color_2', to='store.color'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='logo_color_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logo_color_3', to='store.color'),
        ),
    ]
