# Generated by Django 4.2.7 on 2024-08-21 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_sale_logo_color_1_alter_sale_logo_color_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCodeTypes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('discount', models.FloatField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.promocodetypes')),
            ],
            options={
                'verbose_name': 'Promo Code',
                'verbose_name_plural': 'Promo Codes',
            },
        ),
        migrations.AlterField(
            model_name='sale',
            name='promo_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.promocode'),
        ),
        migrations.DeleteModel(
            name='PromoCodes',
        ),
    ]
