# Generated by Django 4.2.7 on 2024-08-21 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_promocodetypes_promocode_alter_sale_promo_code_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PromoCodeTypes',
            new_name='PromoCodeType',
        ),
        migrations.AlterModelOptions(
            name='promocodetype',
            options={'verbose_name': 'Promo Code Type', 'verbose_name_plural': 'Promo Code Types'},
        ),
    ]
