# Generated by Django 4.2.7 on 2024-08-21 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_rename_promocodetypes_promocodetype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='id',
            field=models.CharField(default='c2d7678c5c964ba2a29055dbf10f51bc', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
