# Generated by Django 4.2.7 on 2024-08-22 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_sale_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='id',
            field=models.CharField(editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
    ]
