# Generated by Django 4.2.7 on 2024-08-22 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_sale_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='color_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='color_set', to='store.color'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='logo_color_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logo_color_1', to='store.color'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='logo_color_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logo_color_2', to='store.color'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='logo_color_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logo_color_3', to='store.color'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.promocode'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.salestatus'),
        ),
    ]
