# Generated by Django 4.2.7 on 2024-08-22 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_sale_color_set_alter_sale_logo_color_1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
    ]
