# Generated by Django 4.2.7 on 2024-08-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_alter_sale_created_at_alter_sale_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
