# Generated by Django 4.2.7 on 2024-08-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_alter_sale_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
