# Generated by Django 4.2.7 on 2024-09-02 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_alter_sale_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addon',
            options={'verbose_name': 'Addon', 'verbose_name_plural': 'Addons'},
        ),
    ]
