# Generated by Django 4.2.7 on 2024-09-24 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_alter_addon_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
