# Generated by Django 4.2.7 on 2024-09-24 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_sale_tracking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='addons',
            field=models.ManyToManyField(blank=True, to='store.addon'),
        ),
    ]
