# Generated by Django 4.2.7 on 2024-09-24 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_alter_sale_addons'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='reminders_sent',
            field=models.IntegerField(default=0),
        ),
    ]
