# Generated by Django 4.2.7 on 2024-10-03 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_sale_reminders_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
