# Generated by Django 4.2.7 on 2024-10-28 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_sale_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='stripe_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
