# Generated by Django 4.2.7 on 2025-04-01 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_sale_stripe_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='stripe_link',
            new_name='payment_link',
        ),
    ]
