# Generated by Django 4.2.7 on 2025-06-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0033_rename_stripe_link_sale_payment_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="invoice_file",
            field=models.FileField(default=1, upload_to="invoice_files"),
            preserve_default=False,
        ),
    ]
