#
# NOTE: THIS DOCKERFILE IS GENERATED VIA "apply-templates.sh"
#
# PLEASE DO NOT EDIT IT DIRECTLY.
#

# Use Python 3.12 slim image
FROM python:3.12-slim

# Load env vars from caprover settings
ARG ENV

ARG SECRET_KEY
ARG DEBUG
ARG HOST
ARG DOMAIN

ARG DB_ENGINE
ARG DB_NAME
ARG DB_USER
ARG DB_PASSWORD
ARG DB_HOST
ARG DB_PORT

ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG AWS_STORAGE_BUCKET_NAME
ARG STORAGE_AWS

ARG EMAIL_HOST
ARG EMAIL_PORT
ARG EMAIL_HOST_USER
ARG EMAIL_HOST_PASSWORD
ARG EMAIL_USE_SSL

ARG TEST_HEADLESS

ARG LANDING_HOST

ARG STRIPE_API_HOST
ARG STRIPE_API_USER

ARG ADMIN_EMAIL
ARG AFFILIATES_COMMISSION
ARG AFFILIATES_DISCOUNT
ARG ALLOWED_ORIGINS
ARG INVOICE_IGI_COMMISSION
ARG INVOICE_PAYPAL_COMMISSION
ARG PAYPAL_API_BASE
ARG PAYPAL_CLIENT_ID
ARG PAYPAL_CLIENT_SECRET
ARG PAYPAL_SANDBOX_PASSWORD
ARG PAYPAL_SANDBOX_USER
ARG FORCE_TESTING_PAYPAL

# Load env vars from caprover settings
ENV ENV=${ENV}

ENV SECRET_KEY=${SECRET_KEY}
ENV DEBUG=${DEBUG}
ENV HOST=${HOST}
ENV DOMAIN=${DOMAIN}

ENV DB_ENGINE=${DB_ENGINE}
ENV DB_NAME=${DB_NAME}
ENV DB_USER=${DB_USER}
ENV DB_PASSWORD=${DB_PASSWORD}
ENV DB_HOST=${DB_HOST}
ENV DB_PORT=${DB_PORT}

ENV AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
ENV AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
ENV AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME}
ENV STORAGE_AWS=${STORAGE_AWS}

ENV EMAIL_HOST=${EMAIL_HOST}
ENV EMAIL_PORT=${EMAIL_PORT}
ENV EMAIL_HOST_USER=${EMAIL_HOST_USER}
ENV EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
ENV EMAIL_USE_SSL=${EMAIL_USE_SSL}

ENV TEST_HEADLESS=${TEST_HEADLESS}

ENV LANDING_HOST=${LANDING_HOST}

ENV STRIPE_API_HOST=${STRIPE_API_HOST}
ENV STRIPE_API_USER=${STRIPE_API_USER}

ENV ADMIN_EMAIL=${ADMIN_EMAIL}
ENV AFFILIATES_COMMISSION=${AFFILIATES_COMMISSION}
ENV AFFILIATES_DISCOUNT=${AFFILIATES_DISCOUNT}
ENV ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
ENV INVOICE_IGI_COMMISSION=${INVOICE_IGI_COMMISSION}
ENV INVOICE_PAYPAL_COMMISSION=${INVOICE_PAYPAL_COMMISSION}
ENV PAYPAL_API_BASE=${PAYPAL_API_BASE}
ENV PAYPAL_CLIENT_ID=${PAYPAL_CLIENT_ID}
ENV PAYPAL_CLIENT_SECRET=${PAYPAL_CLIENT_SECRET}
ENV PAYPAL_SANDBOX_PASSWORD=${PAYPAL_SANDBOX_PASSWORD}
ENV PAYPAL_SANDBOX_USER=${PAYPAL_SANDBOX_USER}
ENV FORCE_TESTING_PAYPAL=${FORCE_TESTING_PAYPAL}

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container
COPY . /app/

# Install system dependencies (e.g., for PostgreSQL support)
RUN apt-get update && apt-get install -y \
    libpq-dev gcc \
    locales \
    && sed -i '/es_ES.UTF-8/s/^# //g' /etc/locale.gen \
    && locale-gen \
    && update-locale LANG=es_ES.UTF-8 LANGUAGE=es_ES:es LC_ALL=es_ES.UTF-8 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN locale-gen es_ES.UTF-8
RUN update-locale

# Install Python dependencies
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Collect static files and migrate database
RUN python manage.py collectstatic --noinput
RUN python manage.py migrate

# Expose the port that Django/Gunicorn will run on
EXPOSE 80

# Command to run Gunicorn with the WSGI application for production
CMD ["gunicorn", "--bind", "0.0.0.0:80", "nyx_dashboard.wsgi:application"]