# Generated by Django 4.2.7 on 2024-06-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='key',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
