# Generated by Django 4.2.7 on 2024-06-21 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_category_text_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.category'),
        ),
    ]
