# Generated by Django 4.2.7 on 2024-07-04 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_video_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Video', 'verbose_name_plural': 'Videos'},
        ),
    ]
