# Generated by Django 4.2.7 on 2024-07-16 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_image_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterModelOptions(
            name='text',
            options={'verbose_name': 'Text', 'verbose_name_plural': 'Texts'},
        ),
    ]
