# Generated by Django 4.2.7 on 2024-09-20 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_alter_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='category',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='text',
            old_name='category',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='category',
            new_name='Category',
        ),
    ]
