# Generated by Django 4.2.7 on 2025-04-11 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='affiliate',
            old_name='promo_code_field',
            new_name='promo_code',
        ),
    ]
