# Generated by Django 4.2.7 on 2025-04-10 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliate',
            name='social_media',
            field=models.URLField(blank=True, help_text='URL de la red social del afiliado', max_length=255, null=True),
        ),
    ]
