# Generated by Django 4.2.7 on 2025-04-11 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_rename_stripe_link_sale_payment_link'),
        ('affiliates', '0002_rename_promo_code_field_affiliate_promo_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comission',
            fields=[
            ],
            options={
                'verbose_name': 'Comisión',
                'verbose_name_plural': 'Comisiones',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('store.sale',),
        ),
    ]
