# Generated by Django 4.2.7 on 2025-04-10 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0002_alter_affiliate_social_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliate',
            name='social_media',
            field=models.URLField(blank=True, help_text='Social media link for the affiliate (e.g., Instagram, Facebook)', max_length=255, null=True),
        ),
    ]
