# Generated by Django 4.2.7 on 2025-04-12 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_rename_stripe_link_sale_payment_link'),
        ('affiliates', '0003_comission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliate',
            name='promo_code',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.promocode', verbose_name='Código promocional'),
        ),
    ]
