# Generated by Django 4.2.7 on 2025-04-22 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_rename_stripe_link_sale_payment_link'),
        ('affiliates', '0006_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comission',
        ),
        migrations.AlterModelOptions(
            name='affiliate',
            options={},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={},
        ),
        migrations.AlterField(
            model_name='payment',
            name='affiliate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='affiliates.affiliate'),
        ),
        migrations.CreateModel(
            name='Comission',
            fields=[
                ('sale_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.sale')),
            ],
            bases=('store.sale',),
        ),
    ]
