# Generated by Django 4.2.7 on 2025-04-22 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_rename_stripe_link_sale_payment_link'),
        ('affiliates', '0007_delete_comission_alter_affiliate_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comission',
        ),
        migrations.CreateModel(
            name='Comission',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('store.sale',),
        ),
    ]
